Repository SALib/SALib, pull requests merged in 2020-09, with the labels that each got.

#310 Example lake problem
  src/SALib/test_functions/lake_problem.py
Labels: documentation, in progress

#298 Uniform console printing
  examples/delta/delta.py
  examples/dgsm/dgsm.py
  examples/fast/fast.py
  examples/rbd_fast/rbd_fast.py
  src/SALib/analyze/delta.py
  src/SALib/analyze/dgsm.py
  src/SALib/analyze/fast.py
  src/SALib/analyze/ff.py
  src/SALib/analyze/morris.py
  src/SALib/analyze/rbd_fast.py
  src/SALib/analyze/sobol.py
  src/SALib/sample/fast_sampler.py
  src/SALib/sample/latin.py
  src/SALib/sample/morris/morris.py
  src/SALib/sample/saltelli.py
  src/SALib/sample/sobol_sequence.py
  src/SALib/test_functions/Ishigami.py
  src/SALib/test_functions/Sobol_G.py
  tests/conftest.py
  tests/sample/morris/test_morris.py
  tests/test_cli_analyze.py
  tests/test_ff.py
  tests/test_sobol.py
  tests/test_util.py
Labels: enhancement

#275 HDMR
  AUTHORS.rst
  docs/index.rst
  examples/hdmr/hdmr.bat
  examples/hdmr/hdmr.py
  examples/hdmr/hdmr.sh
  requirements.txt
  src/SALib/analyze/hdmr.py
  src/SALib/plotting/bar.py
  src/SALib/plotting/hdmr.py
  src/SALib/test_functions/linear_model_1.py
  src/SALib/test_functions/linear_model_2.py
  src/SALib/test_functions/params/case1.txt
  src/SALib/test_functions/params/case2.txt
  src/SALib/test_functions/params/case3.txt
  tests/test_hdmr.py
  tests/test_regression.py
Labels: add_method

#340 Display warning message if seed is set for Saltelli
  src/SALib/sample/saltelli.py
Labels: clean up/maintenance, documentation

#346 Allow alternate sampling distributions for all methods
  README-advanced.md
  docs/advanced.rst
  docs/basics.rst
  docs/index.rst
  src/SALib/sample/fast_sampler.py
  src/SALib/sample/ff.py
  src/SALib/sample/finite_diff.py
  src/SALib/sample/latin.py
  src/SALib/sample/morris/morris.py
  src/SALib/sample/saltelli.py
  src/SALib/util/__init__.py
Labels: enhancement

#339 Problem spec
  examples/Problem/problem_spec.py
  setup.cfg
  src/SALib/__init__.py
  src/SALib/test_functions/Ishigami.py
  src/SALib/util/__init__.py
  src/SALib/util/problem.py
  src/SALib/util/util_funcs.py
Labels: enhancement, in progress
