Repository SALib/SALib, pull requests merged in 2022-09, with the labels that each got.

#522 Make Pathos optional
  examples/Problem/problem_spec.py
  pyproject.toml
  src/SALib/util/problem.py
Labels: clean up/maintenance

#530 Allow seed as CLI option
  src/SALib/sample/sobol.py
Labels: bug

#523 Use pydata-sphinx-theme
  .readthedocs.yml
  CITATIONS.rst
  README.rst
  docs/_static/version_switcher.json
  docs/api.rst
  docs/conf.py
  docs/getting-started.rst
  docs/index.rst
  docs/license.rst
  docs/readme.rst
  environment.yml
  pyproject.toml
Labels: documentation, clean up/maintenance

#526 Heatmap
  examples/plotting/plotting.py
  src/SALib/plotting/heatmap.py
  src/SALib/util/__init__.py
  src/SALib/util/problem.py
Labels: enhancement
