Repository SALib/SALib, pull requests merged in 2024-04, with the labels that each got.

#613 Fix incorrect group display in heatmap plots
  src/SALib/plotting/heatmap.py
  src/SALib/sample/saltelli.py
Labels: bug

#615 Consolidate handling of grouped factors into a single approach
  src/SALib/analyze/morris.py
  src/SALib/analyze/pawn.py
  src/SALib/analyze/rsa.py
  src/SALib/analyze/sobol.py
  src/SALib/plotting/hdmr.py
  src/SALib/plotting/heatmap.py
  src/SALib/sample/morris/morris.py
  src/SALib/util/__init__.py
  src/SALib/util/problem.py
  src/SALib/util/util_funcs.py
Labels: clean up/maintenance

#616 Update maintainer docs
  .github/workflows/release.yaml
  AUTHORS.rst
  CONTRIBUTING.md
Labels: documentation
